server:
  port: 8080

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  profiles:
    default: local

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service-auth
              uri: ${USER_SERVICE_URI}
              predicates:
                - Path=/api/v1/auth/**
            - id: user-service-users
              uri: ${USER_SERVICE_URI}
              predicates:
                - Path=/api/v1/users/**
            - id: wallet-service
              uri: ${WALLET_SERVICE_URI}
              predicates:
                - Path=/api/v1/wallets/me,/api/v1/wallets/me/**
            - id: wallet-service-topup
              uri: ${WALLET_SERVICE_URI}
              predicates:
                - Path=/api/v1/topup,/api/v1/topup/**
            - id: transaction-service
              uri: ${TRANSACTION_SERVICE_URI}
              predicates:
                - Path=/api/v1/transfers,/api/v1/transfers/**
            - id: merchant-service
              uri: ${MERCHANT_SERVICE_URI}
              predicates:
                - Path=/api/v1/merchants/**,/api/v1/admin/merchants/**,/api/v1/qr/**,/api/v1/notifications/**
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - http://localhost:5173 # Vite mặc định
                  # - http://localhost:3000 # nếu UI chạy React/Next ở port 3000
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                exposedHeaders:
                  - Authorization
                allowCredentials: true
                maxAge: 3600
payflow:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-minutes: 15
    refresh-token-expiration-minutes: 10080

management:
  endpoints:
    web:
      exposure:
        include: health,info
